name: Linter

on:
  push:
    branches:
      - modul_1_lenko

jobs:
  lint:
    name: Run linter
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Check if node_modules exists
        run: test -d node_modules || echo 'node_modules not found'

      - name: Install dependencies
        if: steps.node_modules.outputs.exit-code != 0
        run: npm install

      - name: Run linter
        run: npm run lint
