name: Linter

on:
  push:
    branches:
      - modul_1_lenko

jobs:
  lint:
    name: Run linter
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run linter
        run: npm run lint
